"""Interactive installation & provider assistant.

Run ``python setup.py`` to choose an LLM provider, validate credentials, pick a
workspace path and write a structured ``.env`` file. Uses ``rich`` for a clean
CLI experience and degrades gracefully to plain ``input()`` if it is missing.
"""

from __future__ import annotations

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
ENV_PATH = PROJECT_ROOT / ".env"
DEFAULT_WORKSPACE = PROJECT_ROOT / "workspace"

PROVIDERS = {
    "1": ("openai", "OpenAI (GPT-4o)", "gpt-4o", True),
    "2": ("anthropic", "Anthropic (Claude 3.5 Sonnet)", "claude-3-5-sonnet-latest", True),
    "3": ("gemini", "Google Gemini (Gemini 1.5 Pro)", "gemini-1.5-pro", True),
    "4": ("ollama", "Ollama (local)", "llama3.1", False),
}

# Rudimentary per-provider API-key format checks.
KEY_PATTERNS = {
    "openai": re.compile(r"^sk-[A-Za-z0-9_\-]{20,}$"),
    "anthropic": re.compile(r"^sk-ant-[A-Za-z0-9_\-]{20,}$"),
    "gemini": re.compile(r"^[A-Za-z0-9_\-]{30,}$"),
}

try:  # Optional rich UI
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt
    from rich.table import Table

    _console: "Console | None" = Console()
except ImportError:  # pragma: no cover - fallback path
    _console = None


def _print(message: str) -> None:
    if _console:
        _console.print(message)
    else:
        print(message)


def _ask(prompt: str, default: str = "", password: bool = False) -> str:
    if _console:
        return Prompt.ask(prompt, default=default or None, password=password)
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _choose_provider() -> tuple[str, str, bool]:
    if _console:
        table = Table(title="Select an LLM provider", show_header=True, header_style="bold cyan")
        table.add_column("#", justify="center")
        table.add_column("Provider")
        table.add_column("Default model")
        for key, (_, label, model, _needs) in PROVIDERS.items():
            table.add_row(key, label, model)
        _console.print(table)
    else:
        print("\nSelect an LLM provider:")
        for key, (_, label, model, _needs) in PROVIDERS.items():
            print(f"  {key}) {label} — {model}")

    while True:
        choice = _ask("Provider", default="1")
        if choice in PROVIDERS:
            provider, label, model, needs_key = PROVIDERS[choice]
            _print(f"[green]Selected:[/green] {label}" if _console else f"Selected: {label}")
            return provider, model, needs_key
        _print("[red]Invalid choice. Try again.[/red]" if _console else "Invalid choice. Try again.")


def _validate_key(provider: str, key: str) -> bool:
    pattern = KEY_PATTERNS.get(provider)
    if pattern is None:
        return True
    return bool(pattern.match(key))


def _collect_api_key(provider: str) -> str:
    while True:
        key = _ask(f"Enter the {provider} API key", password=True)
        if not key:
            _print("[red]An API key is required for this provider.[/red]" if _console else "API key required.")
            continue
        if _validate_key(provider, key):
            return key
        warn = (
            f"The key does not look like a valid {provider} key. Use it anyway? (y/N)"
        )
        if _ask(warn, default="N").lower().startswith("y"):
            return key


def _write_env(values: dict[str, str]) -> None:
    lines = ["# Generated by setup.py — do not commit.", ""]
    lines.extend(f"{name}={value}" for name, value in values.items())
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    banner = "Aegis-X Enterprise — Interactive Setup"
    if _console:
        _console.print(Panel.fit(banner, style="bold magenta"))
    else:
        print("=" * len(banner) + f"\n{banner}\n" + "=" * len(banner))

    if ENV_PATH.exists():
        overwrite = _ask(".env already exists. Overwrite? (y/N)", default="N")
        if not overwrite.lower().startswith("y"):
            _print("Aborted; existing .env left untouched.")
            return

    provider, default_model, needs_key = _choose_provider()
    model = _ask("Model identifier", default=default_model)

    values: dict[str, str] = {"PROVIDER": provider, "MODEL": model}

    if needs_key:
        values["API_KEY"] = _collect_api_key(provider)
    else:
        base_url = _ask("Ollama base URL", default="http://localhost:11434")
        values["OLLAMA_BASE_URL"] = base_url

    workspace = _ask("Workspace directory", default=str(DEFAULT_WORKSPACE))
    workspace_path = Path(workspace).expanduser().resolve()
    workspace_path.mkdir(parents=True, exist_ok=True)
    values["WORKSPACE_DIR"] = str(workspace_path)

    host = _ask("Web server host", default="127.0.0.1")
    port = _ask("Web server port", default="8000")
    values["HOST"] = host
    values["PORT"] = port

    _write_env(values)

    done = f"Configuration written to {ENV_PATH}"
    if _console:
        _console.print(Panel.fit(done, style="bold green"))
        _console.print("Run [bold]python main.py[/bold] to launch the dashboard.")
    else:
        print(done)
        print("Run `python main.py` to launch the dashboard.")


if __name__ == "__main__":
    main()
